#!/bin/bash
#icon="/home/kessler/pics/icons/$1"

# center screen
#/home/kessler/.linuxbrew/bin/feh -. -x -g +1000+500 /home/kessler/pics/icons/checkered-flag.png

# standard toast style (but permanent)
/home/kessler/.linuxbrew/bin/feh -. -x -g 150x150-1 /home/kessler/pics/icons/checkered-flag.png


#sleep .1
#/home/kessler/.linuxbrew/bin/xdotool key Super+Tab
