#!/bin/bash

#fontstr="Menlo $1"
dconf write /org/gnome/desktop/interface/monospace-font-name "'Menlo $1'"



# the below is all redundant (instead use system wide monospace setting above)

## local
#key='/org/gnome/terminal/legacy/profiles:/:425cff8d-2fe7-49e0-850a-2d5953a7164a/font'
#dconf write $key "'Menlo $1'"
#
### rhino
#key='/org/gnome/terminal/legacy/profiles:/:0b06c44c-ba09-451d-95d5-405fbbac85d1/font'
#dconf write $key "'Menlo $1'"
#
## bear
#key='/org/gnome/terminal/legacy/profiles:/:b9124069-4e11-41f6-ba67-fa25ddffd6d7/font'
#dconf write $key "'Menlo $1'"
#
## turquoise (cheyenne?)
#key='/org/gnome/terminal/legacy/profiles:/:5594c966-cace-47bc-89a0-680b53a9a013/font'
#dconf write $key "'Menlo $1'"
#
## latenight
#key='/org/gnome/terminal/legacy/profiles:/:20998e02-8c01-4670-aab8-2ef16bb557cf/font'
#dconf write $key "'Menlo $1'"
#
##flux
#key='/org/gnome/terminal/legacy/profiles:/:5d667012-532b-46e5-9927-ff5111f95d91/font'
#dconf write $key "'Menlo $1'"


