#!/bin/bash
sleep .1
xdotool key super+Up # detach window if necessary
#xdotool key control+l # clear screen doesn't work
sleep .5
xdotool key --clearmodifiers shift+F10 r 7
sleep .5
#wmctrl -r :ACTIVE: -e 0,10000,0,300,100 # move to top right
wmctrl -r :ACTIVE: -e 0,10000,0,300,50  
wmctrl -r :ACTIVE: -N TIMER # rename window
#wmctrl -r :ACTIVE: -b add,above



start=$(date +%s)  #define date in epoch seconds
diff=$(( $(date +%s) - $start ))    #define difference 

while true; do
	echo -ne "$(date -u -d @$diff +%H:%M:%S )\r"
	diff=$(( `date +%s` -start ))    #define difference 
	sleep 1;
done

	

